name: Hunt me down

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  run-selenium:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up env
        run: |
          sudo apt-get update


      - name: Run Tests with Maven
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_RECEIVER: ${{ secrets.TWILIO_RECEIVER }}
        run: mvn clean test

      - name: Commit and push data
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add amz.csv
          git commit -m "Update watch prices - $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}